#!/usr/bin/env bash
# ═══════════════════════════════════════════════════════════════
# Demonstração dos Comandos de Atualização (SEM executar)
# ═══════════════════════════════════════════════════════════════
# Este script mostra os comandos que você deve executar
# para atualizar o NAP no seu sistema Ubuntu/Debian.
# ═══════════════════════════════════════════════════════════════

echo "╔══════════════════════════════════════════════════════════════╗"
echo "║   🔄 DEMONSTRAÇÃO: Atualização do NAP no Linux            ║"
echo "╚══════════════════════════════════════════════════════════════╝"
echo ""

echo "📍 PASSO 1: Verificar versão atual instalada"
echo "─────────────────────────────────────────────────────────────"
echo "Comando:"
echo "  dpkg -l | grep nap-nexus"
echo ""
echo "Saída esperada:"
echo "  ii  nap-nexus  0.1.0-1  amd64  NAP - Nexus AI Platform"
echo ""
echo "─────────────────────────────────────────────────────────────"
echo ""

echo "📍 PASSO 2: Compilar nova versão (se necessário)"
echo "─────────────────────────────────────────────────────────────"
echo "Comando:"
echo "  ./build.sh --linux"
echo ""
echo "Isso vai gerar: dist/nap_0.2.0-1_amd64.deb"
echo ""
echo "─────────────────────────────────────────────────────────────"
echo ""

echo "📍 PASSO 3: Fazer backup do binário atual (RECOMENDADO)"
echo "─────────────────────────────────────────────────────────────"
echo "Comando:"
echo "  sudo cp /usr/local/bin/nap /usr/local/bin/nap.backup"
echo ""
echo "Isso cria um backup caso precise voltar para a versão anterior"
echo ""
echo "─────────────────────────────────────────────────────────────"
echo ""

echo "📍 PASSO 4: Instalar o novo pacote .deb"
echo "─────────────────────────────────────────────────────────────"
echo "Comando:"
echo "  sudo dpkg -i dist/nap_0.2.0-1_amd64.deb"
echo ""
echo "O que vai acontecer:"
echo "  ✅ Pacote será instalado em /usr/local/bin/nap"
echo "  ✅ Versão anterior será sobrescrita"
echo "  ✅ Script pós-instalação será executado"
echo "  ✅ Configurações serão preservadas"
echo ""
echo "─────────────────────────────────────────────────────────────"
echo ""

echo "📍 PASSO 5: Verificar nova versão instalada"
echo "─────────────────────────────────────────────────────────────"
echo "Comando:"
echo "  dpkg -l | grep nap-nexus"
echo ""
echo "Saída esperada:"
echo "  ii  nap-nexus  0.2.0-1  amd64  NAP - Nexus AI Platform"
echo ""
echo "─────────────────────────────────────────────────────────────"
echo ""

echo "📍 PASSO 6: Testar a nova instalação"
echo "─────────────────────────────────────────────────────────────"
echo "Comando:"
echo "  nap"
echo ""
echo "Isso deve iniciar o NAP com a nova versão"
echo ""
echo "─────────────────────────────────────────────────────────────"
echo ""

echo "📍 PASSO 7: Limpar backup (se tudo funcionou)"
echo "─────────────────────────────────────────────────────────────"
echo "Comando:"
echo "  sudo rm /usr/local/bin/nap.backup"
echo ""
echo "─────────────────────────────────────────────────────────────"
echo ""

echo "╔══════════════════════════════════════════════════════════════╗"
echo "║   ✅ ALTERNATIVA: Usar script automatizado              ║"
echo "╚══════════════════════════════════════════════════════════════╝"
echo ""
echo "Em vez de fazer manualmente, você pode usar:"
echo ""
echo "  sudo ./docs/update_linux.sh"
echo ""
echo "Este script executa todos os passos acima automaticamente:"
echo "  ✅ Verifica versão atual"
echo "  ✅ Faz backup"
echo "  ✅ Instala novo pacote"
echo "  ✅ Verifica nova versão"
echo "  ✅ Limpa backup"
echo ""
echo "─────────────────────────────────────────────────────────────"
echo ""

echo "📍 COMANDOS ÚTEIS"
echo "─────────────────────────────────────────────────────────────"
echo ""
echo "Verificar localização do binário:"
echo "  which nap"
echo ""
echo "Verificar permissões:"
echo "  ls -l /usr/local/bin/nap"
echo ""
echo "Desinstalar (manter configs):"
echo "  sudo dpkg -r nap-nexus"
echo ""
echo "Desinstalar (remover tudo):"
echo "  sudo dpkg -P nap-nexus"
echo ""
echo "Restaurar backup (se algo der errado):"
echo "  sudo cp /usr/local/bin/nap.backup /usr/local/bin/nap"
echo ""
echo "─────────────────────────────────────────────────────────────"
echo ""

echo "📍 FLUXO COMPLETO (Copia e Cola)"
echo "─────────────────────────────────────────────────────────────"
echo ""
echo "# 1. Ir para o diretório do projeto"
echo "cd /home/ghost/Documents/Projetos/0\ -\ NAP_Nexus\ AI\ Platform"
echo ""
echo "# 2. Compilar nova versão"
echo "./build.sh --linux"
echo ""
echo "# 3. Atualizar (uma das opções)"
echo "# Opção A: Manual"
echo "sudo dpkg -i dist/nap_0.2.0-1_amd64.deb"
echo ""
echo "# Opção B: Automática (RECOMENDADA)"
echo "sudo ./docs/update_linux.sh"
echo ""
echo "# 4. Verificar versão"
echo "dpkg -l | grep nap-nexus"
echo ""
echo "# 5. Testar"
echo "nap"
echo ""
echo "─────────────────────────────────────────────────────────────"
echo ""
